name: barber
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  overlay_support: ^1.2.1
  states_rebuilder: ^4.0.0+1
  http: ^0.13.0
  scrollable_positioned_list: ^0.1.10
  cached_network_image: ^3.0.0
  persistent_bottom_nav_bar: ^4.0.2
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  cupertino_icons: ^1.0.0
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.1
  flutter_masked_text: ^0.8.0
  photo_view: ^0.12.0
  flutter_phoenix: ^1.0.0
  path_provider: ^2.0.2
  shimmer: ^2.0.0

dev_dependencies:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/line.png
    - assets/translations/
  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 600
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 100
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: dmserif
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
          style: italic
